version: 2.1

executors:
  ubuntu-build:
    description: "A regular build executor based on ubuntu image"
    docker:
      - image: jovobe/tsl-build-docker-test:latest
    working_directory: /source

jobs:
  build:
    executor: ubuntu-build
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: cd /build && cmake /source/tse -DCMAKE_BUILD_TYPE=Release
      - run: cmake --build /build
      - run: cmake --build /build --target tsl_tests
      - persist_to_workspace:
          root: /build
          paths:
            - tsl/test/src/tsl_tests

  test:
    executor: ubuntu-build
    steps:
      - checkout
      - attach_workspace:
          at: /build
      - run: cd /source/tsl && /build/tsl/test/src/tsl_tests

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
