version: 2.1

orbs:
  slack: circleci/slack@3.4.2

executors:
  ubuntu-build:
    description: "A regular build executor based on ubuntu image"
    docker:
      - image: jdc6284/tsl-test
    working_directory: /home/git/tsl

jobs:
  build:
    executor: ubuntu-build
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: cd /home/build && cmake /home/git/tsl/tse -DCMAKE_BUILD_TYPE=Release
      - run: cmake --build /home/build
      - run: cmake --build /home/build --target tsl_tests
      - persist_to_workspace:
          root: /home/build
          paths:
            - tsl/test/src/tsl_tests

  test:
    executor: ubuntu-build
    steps:
      - checkout
      - attach_workspace:
          at: /home/build
      - run: cd /home/git/tsl/tsl && /home/build/tsl/test/src/tsl_tests
      - slack/status:
          fail_only: false

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
